data-pipeline:
  - changed-files:
    - any-glob-to-any-file: 'MRI_net/data.py'

training:
  - changed-files:
    - any-glob-to-any-file:
      - 'MRI_net/train.py'
      - 'MRI_net/main.py'

model:
  - changed-files:
    - any-glob-to-any-file: 'MRI_net/model.py'

evaluation:
  - changed-files:
    - any-glob-to-any-file: 'MRI_net/evaluation.py'

config:
  - changed-files:
    - any-glob-to-any-file: 'MRI_net/config.py'

api:
  - changed-files:
    - any-glob-to-any-file: 'MRI_net/api.py'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'README.md'
      - 'CONTRIBUTING.md'